### ISSUE TITLE
关于前端UII/UX的改进建议

### ISSUE THREAD

**Issue by slime-butter** [vrcd-community/vpm-repos-syncronizer-web#2]
1. 目前我们通过patcher装配官方镜像源（official，currate），**建议删除VPM镜像站中的官方镜像源链接.**
2. 用户反馈VPM镜像站主页不直观，有操作障碍，网站元素与逻辑的重新设计将在此处[pixso文档](https://pixso.cn/app/editor/7TniiDyJwdvHOVLWz_30UA?page-id=0%3A1 )中进行。

**Comment by Misaka-L** [comment]
close by #10
